config/routes.rb
Rails.application.routes.draw do

  root 'main#index'

  get '/login', to: 'account#login', as: :login
  post '/login', to: 'account#do_login', as: :login_post
  get '/logout', to: 'account#do_logout', as: :logout
  get '/register', to: 'account#register', as: :register
  post '/register', to: 'account#do_register', as: :register_post
  get '/register/success', to: 'account#success_registration', as: :success_registration
  get '/confirm/:code', to: 'account#confirm', as: :confirm_account

  get '/dashboard', to: 'dashboard#index', as: :dashboard

  get '/transaction', to: 'transaction#index', as: :transactions_index
  get '/transaction/new/(:mode)', to: 'transaction#new', as: :new_transaction
  post '/transaction/new', to: 'transaction#create', as: :create_transaction

  get '/wallet', to: 'wallet#index', as: :wallets_index
  get '/wallet/new', to: 'wallet#new', as: :new_wallet
  post '/wallet/new', to: 'wallet#create', as: :create_wallet

  get '/product', to: 'product#index', as: :products_index

  get '/tag', to: 'tag#index', as: :tags_index
  post '/tag/new', to: 'tag#create', as: :create_tag

  get '/book', to: 'book#index', as: :books_index
  get '/book/current', to: 'book#current', as: :current_book
  post '/book/choose', to: 'book#choose', as: :choose_book
  get '/book/new', to: 'book#new', as: :new_book
  post '/book/new', to: 'book#create', as: :create_book
  get '/book/:key', to: 'book#details', as: :book_details
  post '/book/:key', to: 'book#update', as: :update_book

  namespace :data do
    get '/country', to: 'country#index', as: :countries_index
    get '/country/:code/currencies', to: 'country#currencies', as: :country_currencies_index

    get '/currency', to: 'currency#index', as: :currencies_index
    get '/currency/rate', to: 'currency#rate', as: :currencies_rate

    get '/unit', to: 'unit#index', as: :units_index
  end

  namespace :admin do
    get '/', to: 'main#index', as: :main

    get '/user', to: 'user#index', as: :users_index
    post '/user', to: 'user#create', as: :create_user
    post '/user/:user_name/send_email', to: 'user#send_confirmation_email', as: :send_user_confirmation_email
    patch '/user/:user_name', to: 'user#update', as: :update_user

    get '/invite', to: 'invite#index', as: :invites_index
    post '/invite', to: 'invite#create', as: :create_invite
    delete '/invite/:code', to: 'invite#delete', as: :delete_invite
  end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_filter :authorize
  before_filter :need_book

  def index
    @book = current_book
  end

end

app/views/dashboard/index.html.haml
-content_for :styles do
  =stylesheet_link_tag 'views/dashboard', media: "all"
-content_for :scripts do
  =javascript_include_tag 'views/dashboard'

.row
  .col-md-8
    = bt_panel ko: 'with: transactions' do |panel|
      - panel.header do
        %span=t('.last_transactions')
        %span.pull-right
          = bt_button text: t('commands.add_transaction'), size: :xsmall, style: :link, href: new_transaction_path
          = bt_icon :spinner, spin: true, ko: 'visible: loading'
          = bt_button icon: :refresh, title: t('commands.refresh'), style: :link, size: :xsmall, |
                       ko: 'click: refresh, visible: !loading()'
      - panel.body do
        %table.transactions
          %tbody(data-bind="foreach: items")
            %tr
              %td.column-info
                %span(data-bind="text: dateText")
                %a{ href: '#' }
                  %img.avatar.s16(data-bind="attr: { src: creator.avatarUrl }")
                  %span(data-bind="text: creator.displayName")
              %td.column-fill
              %td.column-operations
                %ul.operations(data-bind="foreach: operations")
                  %li
                    %img(data-bind="attr: { src: wallet.imageUrl }")
                    %span.name(data-bind="text: wallet.displayName")
                    %span(data-bind="css: { income: type == 'in', outcome: type == 'out' }")
                      %span(data-bind="text: sumText")
                      %span(data-bind="text: currency.code")
  .col-md-4
    = bt_panel do |panel|
      - panel.header do
        %span=t('.current_book', name: @book.display_name)
        %span.pull-right
          = bt_button text: t('commands.change'), size: :xsmall, style: :link, href: books_index_path
      - panel.body do
        %table
    = bt_panel ko: 'with: wallets' do |panel|
      - panel.header do
        %span
          = t('.wallets')
          %span.pull-right
            =bt_button text: t('commands.create'), size: :xsmall, style: :link, href: new_wallet_path
            =bt_icon :spinner, spin: true, ko: 'visible: loading'
            =bt_button icon: :refresh, title: t('commands.refresh'), style: :link, size: :xsmall, |
                       ko: 'click: refresh, visible: !loading()'
      - panel.body do
        %ul.wallets(data-bind="foreach: items")
          %li
            %img(data-bind="attr: { src: image_url }")
            %span.name(data-bind="text: display_name")
    