config/routes.rb
Rails.application.routes.draw do

  root 'main#index'

  get '/login', to: 'account#login', as: :login
  post '/login', to: 'account#do_login', as: :login_post
  get '/logout', to: 'account#do_logout', as: :logout
  get '/register', to: 'account#register', as: :register
  post '/register', to: 'account#do_register', as: :register_post
  get '/register/success', to: 'account#success_registration', as: :success_registration
  get '/confirm/:code', to: 'account#confirm', as: :confirm_account

  get '/dashboard', to: 'dashboard#index', as: :dashboard

  get '/transaction', to: 'transaction#index', as: :transactions_index
  get '/transaction/new/(:mode)', to: 'transaction#new', as: :new_transaction
  post '/transaction/new', to: 'transaction#create', as: :create_transaction

  get '/wallet', to: 'wallet#index', as: :wallets_index
  get '/wallet/new', to: 'wallet#new', as: :new_wallet
  post '/wallet/new', to: 'wallet#create', as: :create_wallet

  get '/product', to: 'product#index', as: :products_index

  get '/tag', to: 'tag#index', as: :tags_index
  post '/tag/new', to: 'tag#create', as: :create_tag

  get '/book', to: 'book#index', as: :books_index
  get '/book/current', to: 'book#current', as: :current_book
  post '/book/choose', to: 'book#choose', as: :choose_book
  get '/book/new', to: 'book#new', as: :new_book
  post '/book/new', to: 'book#create', as: :create_book
  get '/book/:key', to: 'book#details', as: :book_details
  post '/book/:key', to: 'book#update', as: :update_book

  namespace :data do
    get '/country', to: 'country#index', as: :countries_index
    get '/country/:code/currencies', to: 'country#currencies', as: :country_currencies_index

    get '/currency', to: 'currency#index', as: :currencies_index
    get '/currency/rate', to: 'currency#rate', as: :currencies_rate

    get '/unit', to: 'unit#index', as: :units_index
  end

  namespace :admin do
    get '/', to: 'main#index', as: :main

    get '/user', to: 'user#index', as: :users_index
    post '/user', to: 'user#create', as: :create_user
    post '/user/:user_name/send_email', to: 'user#send_confirmation_email', as: :send_user_confirmation_email
    patch '/user/:user_name', to: 'user#update', as: :update_user

    get '/invite', to: 'invite#index', as: :invites_index
    post '/invite', to: 'invite#create', as: :create_invite
    delete '/invite/:code', to: 'invite#delete', as: :delete_invite
  end

end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :owner, class_name: 'User', foreign_key: 'owner_user_id'
  has_and_belongs_to_many :users
  has_and_belongs_to_many :currencies

  has_many :wallets

  validates :key, :display_name, :owner, presence: true
end

app/controllers/book_controller.rb
class BookController < ApplicationController
  before_filter :authorize
  # before_filter :need_book, only: :current

  def index
    @books = current_user.books.order :display_name
  end

  def details
    @book = Book.find_by_key(params.require(:key))
    respond_to do |f|
      f.html do
        return render_not_found unless @book
      end
      f.json do
        return render_api_resp :not_found unless @book
        render_api_resp :ok, data: current_book
      end
    end  
  end

  def current
    @book = current_book
    respond_to do |f|
      f.html do
        need_book 
        render 'details'
      end
      f.json do
        return render_api_resp :ok, message: 'book_not_selected' unless current_book
        render_api_resp :ok, data: current_book
      end
    end    
  end

  def choose
    book = Book.find_by_key(params.require(:key))
    return render_api_resp :not_found unless book
    set_current_book(book)
    return render_api_resp :ok
  end

  def new
    @book = Book.new
  end

  def create
    book = params.require(:book)
    book = Book.new(book.permit(:display_name))
    book.owner = current_user

    params.require(:currencies).each do |code|
      currency = Currency.find_by_code(code)
      book.currencies.push(currency) if (currency) 
    end

    begin
      book.key = SecureRandom.hex(6)
    end while (Book.find_by_key book.key)

    if (book.valid?)
      book.save!
      return redirect_to books_index_path
    end

    @book = book
    render 'new'
  end
  
  def update
    @book = Book.find_by_key(params.require(:key))
    return render_not_found unless @book
    @book.update(params.require(:book).permit(:display_name))
    @book.save! if @book.valid?
    render 'details'
  end

end

app/views/book/details.html.haml
- content_for :styles do
  = stylesheet_link_tag 'views/book', media: "all"

.page-panel
  .page-title= t('.book_details')

  .row
    .col-lg-5
      = bt_form_for @book, style: :horizontal do |f|
        = f.hidden_input property: :key
        = f.group property: :display_name do |g|
          = g.text_input
        = f.group property: :owner do |g|
          = g.static do
            = user_profile_link @book.owner, avatar: :small
        = f.group property: :created_at do |g|
          = g.static do
            = time_tag @book.created_at
        = f.group do |g|
          = g.submit_button text: t('commands.save')
          = bt_button text: t('commands.back'), href: books_index_path

app/views/book/index.html.haml
- content_for :styles do
  = stylesheet_link_tag 'views/book', media: "all"
- content_for :scripts do
  = javascript_include_tag "views/book_index"

.page-panel
  .page-title= t('.books_list')
  .page-description= t('.books_list_desc')
  .page-toolbar.btn-toolbar(role="toolbar")
    = bt_button text: t('commands.create'), href: create_book_path, style: :primary
  - if @books.size == 0
    %span= t('.no_books')
  %table.table.table-hover.books-table
    - @books.each do |book|
      %tr{ :class => (current_book && book.id == current_book.id) ? "success" : "" }
        %td
          .first-row
            %a.book-name{ href: book_details_path(key: book.key) }= book.display_name
            .book-controls
              - unless current_book && book.id == current_book.id
                = bt_button text: t('commands.choose'), icon: :check, size: :xsmall, style: :link,
                            html: { onclick: 'choose(\'' + book.key + '\')' }
          .second-row
            %span
              = t('.book_owner')
              = user_profile_link book.owner, avatar: :small
            %span
              = t('.book_created_at')
              = time_tag book.created_at

app/views/book/new.html.haml
-content_for :styles do
  =stylesheet_link_tag 'views/book', media: "all"
  =stylesheet_link_tag 'views/book_new', media: "all"
-content_for :scripts do
  =javascript_include_tag 'views/book_new'

.page-panel
  .page-title=t('.create_book')
  .page-description=t('.create_book_desc')
  .row
    .col-lg-5
      =bt_form_for @book do |f|
        .form-group
          =f.text_input property: :display_name

        =ko 'with: currencies' do
          .form-group
            %select.form-control{:'data-placeholder' => t('.choose_country'), |
                                 :'data-bind' => 'chosen: true, value: selectedCountry' }
              %option
              -Country.all.order(:name).each do |c|
                %option{value: c.code}=c.name

          =bt_panel header: t('.book_currencies') do
            .input-group
              %select.form-control{ :'data-bind' => 'chosen: true, value: selectedCurrency' }
                -Currency.all.order(:name).each do |c|
                  %option{value: "#{c.code};#{c.name};#{c.symbol}"}=c.name
              %span.input-group-btn
                =bt_button text: t('commands.add'), ko: 'click: addSelected'
            .currencies
              =ko 'if: list_auto().length' do
                %span=t('.currencies_auto')
                %ul(data-bind="template: { name: 'currency-template', foreach: list_auto }")
              =ko 'if: list_manual().length' do
                %span=t('.currencies_manual')
                %ul(data-bind="template: { name: 'currency-template', foreach: list_manual }")
        =f.submit_button text: t('commands.create')
        =bt_button text: t('commands.cancel'), href: books_index_path

=ko_template 'currency-template' do
  %li
    %input(type="hidden" name="currencies[]" data-bind="value: code")
    %span.symbol(data-bind="text: symbol")
    %span.name(data-bind="text: name")
    %span.code(data-bind="text: code")
    %span.controls
      =bt_button size: :xsmall, style: :link, text: t('commands.delete'), ko: 'click: $parent.delete'